### ISSUE TITLE
eu poderia deixar seu codigo com visualização em 3d porem vc criptografou o .js

### ISSUE THREAD

**Issue by fabricocouto** [leomurca/embroidery-viewer#16]
eu poderia deixar seu codigo com visualização em 3d porem vc criptografou o .js

![imagem_2022-12-17_144441058](https://user-images.githubusercontent.com/20323161/208254595-ceb1ca23-a911-4823-9007-971c85c77240.png)

**Comment by fabricocouto** [comment]
seguindo sua idea olha como fica em trueview
![imagem_2022-12-17_190242624](https://user-images.githubusercontent.com/20323161/208267522-d998f051-5ac7-407f-9515-d64759a0c859.png)

**Comment by fabricocouto** [comment]
E tambem pode colocar os tamanhos cores usadas colocar um combo para converter os arquivos
![image](https://user-images.githubusercontent.com/20323161/208305751-6723432c-480d-4557-bc9c-9fae2334d30b.png)

**Comment by leomurca** [comment]
@fabricocouto 
Qual parte está criptografada? Acho uma excelente ideia a visualização 3d e seria uma contribuição muito bem vinda para o projeto. Posso criar uma issue caso possa contribuir. O que acha? :slightly_smiling_face: 

Sobre os tamanhos e cores usadas, confesso que não havia pensado nisso. Mas curti muito a ideia! Vou até criar outra issue para adição dessas funcionalidades. E claro, se quiser e puder contribuir com essas funcionalidades também seria excelente!

Abraço!

**Comment by leomurca** [comment]
Issue criada: #17

**Comment by leomurca** [comment]
Adicionei a funcionalidade de uma visualização 3d mencionado por você. Issue #22 
Muito obrigado pela contribuição.

**Comment by fabricocouto** [comment]
agora vc pode colocar para converter para outras maquinas
![imagem_2023-01-09_111707119](https://user-images.githubusercontent.com/20323161/211328817-f4b211bd-160a-4f80-9d4f-c226a7140abf.png)

**Comment by fabricocouto** [comment]
e talvez imprimir tambem 
![imagem_2023-01-09_112121419](https://user-images.githubusercontent.com/20323161/211329762-638b81ef-f50f-4b9e-8efc-f2f4bfe56fdc.png)

**Comment by fabricocouto** [comment]
em arquivos dst pelo menos aqui no brasil é muito usando lantejoulas e em todos os códigos que aqui tiver nao tem a visualização das lantejoulas vc tambem poderia adicionar.
eu estou nesses código a mais de 10 anos, ajudei e escrevi em diversas linguagens ate em vb6 
![imagem_2023-01-09_112802637](https://user-images.githubusercontent.com/20323161/211331322-b5c8d99b-b12f-43b4-81af-865a3f4ee9fc.png)

**Comment by fabricocouto** [comment]
depois se quiser me chama no hangout
fabriciocoutodivino@gmail.com

**Comment by fabricocouto** [comment]
você também esta seguindo uma base antiga de html para visualizar eu recomendo você reescrever  visualização pelo codigo py do https://github.com/tatarize
expert nesses arquivos binários eu escrevi em js puro na base que eu escrevi em c#  e escrevi minha base em c# pela base qdo tartarize tanto para ler e para escrever, escrever é mais difícil do que ler porque vc tem que intender cada byte

aqui vc tem vários formatos documentados 
https://edutechwiki.unige.ch/en/Embroidery_format_PES

**Comment by fabricocouto** [comment]
a escritas desses arquivos tem que ser extremamente certa, porque se nao a maquina não os reconhece,
![Uploading imagem_2023-01-09_115938146.png…]()

**Comment by fabricocouto** [comment]
a escritas desses arquivos tem que ser extremamente certa, porque se nao a maquina não os reconhece,

![imagem_2023-01-09_115953256](https://user-images.githubusercontent.com/20323161/211338420-6bc42699-0403-4604-839a-13e3e809dcaf.png)

**Comment by fabricocouto** [comment]
você tambem deve corrigir a visualização para pes esta fora do eixo
![imagem_2023-01-09_141650118](https://user-images.githubusercontent.com/20323161/211367800-8eee4972-33d3-4fc9-9147-a0fecbc8ee4d.png)
